const PROMISE = 'PROMISE';
const SET_COVID_DATA = 'SET_COVID_DATA ';
const SORT_COVID_DATA_ASC = 'SORT_COVID_DATA_ASC';
const SORT_COVID_DATA_DESC = 'SORT_COVID_DATA_DESC';
const SHOW_COUNTRY_DETAILS = 'SHOW_COUNTRY_DETAILS';
const HIDE_COUNTRY_DETAILS = 'HIDE_COUNTRY_DETAILS';
const SET_COUNTRY_DETAILS_DATA = 'SET_COUNTRY_DETAILS_DATA';

export {
  PROMISE,
  SET_COVID_DATA,
  SORT_COVID_DATA_ASC,
  SORT_COVID_DATA_DESC,
  SHOW_COUNTRY_DETAILS,
  HIDE_COUNTRY_DETAILS,
  SET_COUNTRY_DETAILS_DATA,
}
