const PROMISE = 'PROMISE';
const SET_COVID_DATA = 'SET_COVID_DATA ';
const SORT_COVID_DATA_ASC = 'SORT_COVID_DATA_ASC';
const SORT_COVID_DATA_DESC = 'SORT_COVID_DATA_DESC';
const FILTER_COVID_DATA = 'FILTER_COVID_DATA';

export {
  PROMISE,
  SET_COVID_DATA,
  SORT_COVID_DATA_ASC,
  SORT_COVID_DATA_DESC,
  FILTER_COVID_DATA,
}
